const usernames: string[] = [
  'StreamerFan123',
  'GamingGuru',
  'TwitchLover',
  'ProPlayer99',
  'ChatKing',
  'StreamMaster',
  'GamerGirl',
  'KeyboardWarrior',
  'TwitchNinja',
  'StreamerLegend',
  'ChatterBox',
  'GamingAddict',
  'TwitchFanatic',
  'ProStreamer',
  'ChatWizard',
  'GamerGuy',
  'TwitchPro',
  'StreamerHero',
  'ChatMaster',
  'GamingLegend',
]

const badMessages: string[] = [
  'This game is so boring!',
  'You suck at this!',
  'Why are you even streaming this?',
  'Get better at the game!',
  'This is so cringe!',
  'You need to practice more!',
  'This is not entertaining at all!',
  'I’m out, this is too slow!',
  'You’re not funny!',
  'This stream is a waste of time!',
  'You’re not even trying!',
  'This is the worst stream ever!',
  'I’m unsubscribing!',
  'You’re not good enough!',
  'This is so lame!',
  'You’re not entertaining!',
  'This is not worth watching!',
  'You’re not funny at all!',
  'This is so boring!',
  'You’re not good at this!',
]

const goodMessages: string[] = [
  'Keep it up!',
  'You’re doing great!',
  'Love your stream!',
  'You’re amazing!',
  'This is so fun!',
  'You’re the best!',
  'I’m loving this!',
  'You’re so talented!',
  'This is awesome!',
  'You’re hilarious!',
  'You’re a pro!',
  'This is the best stream ever!',
  'I’m subscribing!',
  'You’re so good at this!',
  'This is so entertaining!',
  'You’re a legend!',
  'This is so cool!',
  'You’re so funny!',
  'This is the best!',
  'You’re a star!',
]

export { usernames, badMessages, goodMessages }
